---
- name: copy to awx
  hosts: 192.168.81.141
  become: true
  tasks:
    - name: festch file
      fetch:
        src: ~/test
        dest: ~/ 
        flat: yes
- name: copy to remote host
  hosts: 192.168.81.155
  become: true
  tasks:
    - name: get file
      copy:
        src: ~/test
        dest: ~/       
